### ISSUE TITLE
cant send file

### ISSUE THREAD

**Issue by xkarosx** [ZinoKader/portal#14]
hi i was just using portal when suddenly
`Error initializing UI unable to set console to raw mode: The parameter is incorrect.`
this error came i cant send any files.

any help would be appreciated.
thanks

**Comment by ZinoKader** [comment]
Hi! Do you per chance use Windows with a version below Windows 10? This issue stems from a transitive dependency. There is a closed issue in the library we use which the dependency comes from, which has a few suggestions: https://github.com/charmbracelet/bubbletea/issues/202.

In short: try using Windows Terminal instead, or upgrade your Windows version.

**Comment by xkarosx** [comment]
Yes i use windows 7
But thanks!
